---
# Variables here are applicable to all host groups
status_dir: "{{ deploy_dir }}/status"
backup_dir: "{{ deploy_dir }}/backup"
images_dir: "{{ deploy_dir }}/images"

# Local
downloads_dir: "{{ package_dir }}/downloads"
resources_dir: "{{ package_dir }}/resources"
fetch_tmp_dir: "{{ playbook_dir }}/fetch_tmp"
fetch_log_dir: "{{ playbook_dir }}/fetch_log"

# default configuration for multiple host groups and roles
node_exporter_port: 9100
blackbox_exporter_port: 9115

# docker
docker_bin_dir: "/usr/bin"

# Random shifts for retrying failed ops like downloading
retry_stagger: 5

dev_mode: False
