---

- name: create deploy directories
  file: path={{ item }} state=directory mode=0755
  with_items:
  - "{{ prometheus_log_dir }}"
  - "{{ prometheus_data_dir }}"
  - "{{ deploy_dir }}/status/{{ role_name }}"

# FIXME: how to handle customized alert.rules & config file
- name: get config file stat
  stat: path={{ deploy_dir }}/conf/prometheus@{{ prometheus_port }}.yml
  register: st_conf

- name: get alert conf stat
  stat: path={{ deploy_dir }}/conf/alert.rules@{{ prometheus_port }}.yml
  register: st_alert_conf

- name: create configuration file if not exist
  template: src=prometheus.yml.j2 dest={{ deploy_dir }}/conf/prometheus@{{ prometheus_port }}.yml mode=0644
  vars:
    hosts: "{{ groups['all'] | list }}"

- name: copy alert rules file
  copy: src={{ item }}.yml dest="{{ deploy_dir }}/conf/{{ item }}@{{ prometheus_port }}.yml" mode=0644
  with_items:
    - node.rules
    - bypass.rules
    - pd.rules
    - tidb.rules
    - tikv.rules
    - binlog.rules
    - blacker.rules
    
- name: set alert rules label changes
  replace: >
    dest={{ deploy_dir }}/conf/{{ item }}
    regexp="ENV_LABELS_ENV"
    replace="{{ cluster_name }}"
  with_items:
    - node.rules@{{ prometheus_port }}.yml
    - bypass.rules@{{ prometheus_port }}.yml
    - pd.rules@{{ prometheus_port }}.yml
    - tidb.rules@{{ prometheus_port }}.yml
    - tikv.rules@{{ prometheus_port }}.yml
    - binlog.rules@{{ prometheus_port }}.yml
    - blacker.rules@{{ prometheus_port }}.yml



- name: create deploy data directory
  file: path={{ item }} state=directory mode=0755
  with_items:
  - "{{ prometheus_data_dir }}"

- include: "{{ deployment_method }}_deployment.yml"

- name: prepare firewalld white list
  set_fact:
    firewalld_ports: "{{ [prometheus_port ~ '/tcp'] + firewalld_ports }}"

